// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionEntityUID } from "./ActionEntityUID";
import type { ApplySpec } from "./ApplySpec";
import type { CedarValueJson } from "./CedarValueJson";

export interface ActionType { attributes: Record<string, CedarValueJson> | null, appliesTo: ApplySpec | null, memberOf: Array<ActionEntityUID> | null, }