// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttributesOrContext } from "./AttributesOrContext";

export interface ApplySpec { resourceTypes: Array<string> | null, principalTypes: Array<string> | null, context: AttributesOrContext, }