// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InterfaceResponse } from "./InterfaceResponse";

export type AuthorizationAnswer = { errors: Array<string>, } | { response: InterfaceResponse, };