// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FnAndArg } from "./FnAndArg";
import type { TypeAndId } from "./TypeAndId";

export type CedarValueJson = { __expr: string, } | { __entity: TypeAndId, } | { __extn: FnAndArg, } | boolean | bigint | string | Array<CedarValueJson> | Record<string, CedarValueJson>;