// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CedarValueJson } from "./CedarValueJson";
import type { EntityUidJson } from "./EntityUidJson";

export interface EntityJson { uid: EntityUidJson, attrs: Record<string, CedarValueJson>, parents: Array<EntityUidJson>, }