// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttributesOrContext } from "./AttributesOrContext";

export interface EntityType { memberOfTypes: Array<string>, shape: AttributesOrContext, }