// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TypeAndId } from "./TypeAndId";

export type EntityUidJson = { __expr: string, } | { __entity: TypeAndId, } | string | TypeAndId;