// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Decision } from "./Decision";
import type { InterfaceDiagnostics } from "./InterfaceDiagnostics";

export interface InterfaceResponse { decision: Decision, diagnostics: InterfaceDiagnostics, }