// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionType } from "./ActionType";
import type { EntityType } from "./EntityType";
import type { SchemaType } from "./SchemaType";

export interface NamespaceDefinition { commonTypes: Record<string, SchemaType>, entityTypes: Record<string, EntityType>, actions: Record<string, ActionType>, }