// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityJson } from "./EntityJson";
import type { PolicySpecification } from "./PolicySpecification";
import type { TemplateLink } from "./TemplateLink";

export interface RecvdSlice { policies: PolicySpecification, entities: Array<EntityJson>, templates: Record<string, string> | null, template_instantiations: Array<TemplateLink> | null, }