// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SchemaTypeVariant } from "./SchemaTypeVariant";

export type SchemaType = SchemaTypeVariant | { type: string, };