// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SchemaType } from "./SchemaType";
import type { TypeOfAttribute } from "./TypeOfAttribute";

export type SchemaTypeVariant = { "type": "String" } | { "type": "Long" } | { "type": "Boolean" } | { "type": "Set", element: SchemaType, } | { "type": "Record", attributes: Record<string, TypeOfAttribute>, additionalAttributes: boolean, } | { "type": "Entity", name: string, } | { "type": "Extension", name: string, };