// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Link } from "./Link";

export interface TemplateLink { template_id: string, result_policy_id: string, instantiations: Array<Link>, }