// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NestedSchemaTypeVariant } from "./NestedSchemaTypeVariant";

export type TypeOfAttribute = NestedSchemaTypeVariant | { type: string, required: boolean, };